version: '3.3'
services:
  sql-db:
    container_name: mysql-container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
        -  6603:3306
    volumes:
        - sql-volumes:/var/lib/mysql
        - ./sql-files:/root/sql-files

  python-env:
    build: .
    image: py_test_image
    container_name: python-container
    volumes:
      - ./app:/home/app_user/app
    stdin_open: true
    tty: true
        
volumes:
  sql-volumes:
