#version: '3.3'
services:
  sql-db:
    build: ./sql-service
    image: sql_image
    container_name: capstone-mysql
    restart: always
    ports:
        -  6603:3306
    volumes:
        - sql-volumes:/var/lib/mysql
        - ./sql-service/sql-files:docker-entrypoint-initdb.d

  python-env:
    build: ./py-service
    image: py_test_image
    container_name: capstone-python
    volumes:
      - ./py-service/app:/home/app_user/app
    stdin_open: true
    tty: true
        
volumes:
  sql-volumes: