--This is where we'll create a template for a database.

--Now the question is, what do we put here?

--If we're selling furniture, textbooks, and supplies...

--An item should have a name, a type (maybe an enum? Maybe we have to specify it in text), a price, the seller's name, maybe whether it's sold? So maybe a Boolean...

--I guess we can talk more in detail about it at the next meeting, but...