FROM mysql:8.4

# Set environment variables
ENV MYSQL_ROOT_PASSWORD="root"
ENV MYSQL_DATABASE="mizzou_marketplace"
ENV MYSQL_USER="db_user"
ENV MYSQL_PASSWORD="dbpass"


# Run the MySQL server
#CMD ["bash"]
#CMD ["mysql", "-u root", "-p${MYSQL_ROOT_PASSWORD}"]
